#!/bin/bash
#
# Filter firmware modinfo against the list of files in linux-firmware.
#
ff=/tmp/$$

if [ "$1" = "" ]
then
	echo You must supply a fwinfo file from getabi
	exit 1
fi

find . -type f|sed 's/\.\///'|egrep -v "debian|\.git|WHENCE|LICEN" |\
while read f
do
	rm -f $ff
	cat $1 | while read fw
	do	
		if [ "$f" = "$fw" ]
		then
			echo $f > $ff
			break
		fi
	done
	if [ ! -f $ff ]
	then
		echo $f
	fi
done
